fix: move Page.Resources to top of VideoPlayerPage.xaml
StaticResource is resolved at XAML parse time (top-to-bottom). MuteIconStyle
was defined in a <Page.Resources> block at the *bottom* of the file, after
the ui:SymbolIcon that references it at line 108. This caused:

  XamlParseException: 'Cannot find resource named MuteIconStyle'
  at System.Windows.Markup.XamlReader.RewrapException (line 108, pos 38)

Fix: move <Page.Resources> to immediately after the <Page> opening tag so
all styles are resolved before any element references them.